---

- hosts: webservers
  user: vagrant
  sudo: True

  vars_files:
      - vars.yml

  tasks:
    - include: webserver.yml

    - name: deploy code from repository
      action: git repo=$repo_url dest=${webapps_dir}/${app_name} remote=$repo_remote version=$repo_version
      notify:
        - restart app

    - name: create supervisor program config
      action: template src=templates/supervisor.ini dest=/etc/supervisor/${app_name}.ini
      notify:
        - restart app

    - name: create nginx site config
      action: template src=templates/nginx_site.conf dest=/etc/nginx/sites-available/${app_name}.conf
      notify:
        - restart nginx

    - include: deploy-base.yml

  handlers:
    - include: handlers.yml
