---

- hosts: webservers
  user: vagrant
  sudo: True

  vars:
    app_name: flask_skeleton
    repo_url: https://github.com/mattupstate/vagrant-ansible-tutorial.git
    repo_remote: origin
    repo_version: master
    webapps_dir: /srv
    webapp_port: 8000

  tasks:
    - name: deploy code from repository
      action: git repo=$repo_url dest=${webapps_dir}/${app_name} remote=$repo_remote version=$repo_version
      notify:
        - restart app

    - name: install dependencies
      action: pip requirements=${webapps_dir}/${app_name}/requirements.txt state=present

    - name: create supervisor program config
      action: template src=templates/supervisor.ini dest=/etc/supervisor/${app_name}.ini
      notify:
        - restart app

    - name: create nginx site config
      action: template src=templates/nginx_site.conf dest=/etc/nginx/sites-available/${app_name}.conf
      notify:
        - restart nginx

    - name: link nginx config
      action: file src=/etc/nginx/sites-available/${app_name}.conf dest=/etc/nginx/sites-enabled/${app_name}.conf state=link

    - name: add app to supervisor
      action: supervisorctl name=${app_name} state=present

  handlers:
    - name: restart app
      action: supervisorctl name=${app_name} state=restarted

    - name: restart nginx
      action: service name=nginx state=restarted
